=== thinkpavan/artefacts/Java/java_examples Hyd/software/newj2ee/xmlbeans/part3/classes/schema/src/mypo.xsd
<xs:schema
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xmlns:po="http://inetsolv.info/po"
   targetNamespace="http://inetsolv.info/po"
   elementFormDefault="qualified">

  <xs:element name="purchase-order">
    	<xs:complexType>
      	<xs:sequence>
			<xs:element name="customer">
 	 		<xs:complexType>
   	 			<xs:sequence>
     	 				<xs:element name="name" type="xs:string"/>
      				<xs:element name="address" type="xs:string"/>
	    			</xs:sequence>
    					<xs:attribute name="age" type="xs:int"/>
					<xs:attribute name="sa" type="xs:int" fixed="200"/>
	      	</xs:complexType>
			</xs:element>
			<xs:element name="line-item" minOccurs="1" maxOccurs="unbounded">
	 		<xs:complexType>
    				<xs:sequence>
      				<xs:element name="description" type="xs:string"/>
		      		<xs:element name="price" type="xs:decimal"/>
		      		<xs:element name="quantity" type="xs:integer"/>
				</xs:sequence>
			</xs:complexType>
			</xs:element>
      	</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== thinkpavan/artefacts/Java/java_examples Hyd/software/newj2ee/xmlbeans/part3/input1.xml
<?xml version="1.0" encoding="UTF-8"?>
<purchase-order xmlns="http://inetsolv.info/po" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://inetsolv.info/po
D:\xmlbeans\part3\mypo.xsd">
	<customer age="44">
		<name> name of customer</name>
		<address>address of customer</address>
	</customer>
	<line-item>
		<description>pen</description>
		<price>22.22</price>
		<quantity>22</quantity>
	</line-item>
		<line-item>
		<description>pencil</description>
		<price>22.22</price>
		<quantity>22</quantity>
	</line-item>
</purchase-order>
